services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: anankor-backend:latest
    environment:
      - RUST_LOG=info
    depends_on:
      redis:
        condition: service_started
      dynamodb:
        condition: service_healthy

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    image: anankor-bot:latest
    environment:
      - RUST_LOG=info
    depends_on:
      backend:
        condition: service_started
      lavalink:
        condition: service_started

  redis:
    build:
      context: redis
      dockerfile: Dockerfile
    image: anankor-redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis-data:/data

  dynamodb:
    build:
      context: dynamodb
      dockerfile: Dockerfile
    image: anankor-dynamodb:latest
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/shell/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - dynamodb-data:/home/dynamodblocal/data

  lavalink:
    build:
      context: lavalink
      dockerfile: Dockerfile
    image: anankor-lavalink:latest
    environment:
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=youshallnotpass
    ports:
      - "2333:2333"
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:2333/version || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      redis:
        condition: service_started

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - redis

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    ports:
      - "3200:3200"
    volumes:
      - ./infrastructure/tempo/tempo.yaml:/etc/tempo.yaml:ro

  grafana:
    image: grafana/grafana:10.4.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
      - tempo

volumes:
  dynamodb-data:
  redis-data:
  grafana-data:
