server:
  port: 2333
  address: 0.0.0.0

lavalink:
  pluginsDir: "./plugins"
  server:
    password: ${LAVALINK_SERVER_PASSWORD:-youshallnotpass}
    player-update-interval: 5
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    filters:
      volume: true
    soundcloud:
      client-id: ''

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - ANDROID_VR
      - WEB
      - WEBEMBEDDED
      - MUSIC
    remoteCipher:
      url: "${YOUTUBE_REMOTE_CIPHER_URL:-http://yt-cipher:8001}"
      password: "${YOUTUBE_REMOTE_CIPHER_PASSWORD:-}"
      userAgent: "${YOUTUBE_REMOTE_CIPHER_USER_AGENT:-AnankorBot}"
  lavasrc:
    enabled: true
    providers:
      - 'ytsearch:"%ISRC%"'
      - 'ytsearch:%QUERY%'
    sources:
      spotify: true
      applemusic: true
      deezer: false
      yandexmusic: false
      flowerytts: false
      youtube: false
      vkmusic: false
      tidal: false
      qobuz: false
      ytdlp: false
      jiosaavn: false
    spotify:
      clientId: "${SPOTIFY_CLIENT_ID:-}"
      clientSecret: "${SPOTIFY_CLIENT_SECRET:-}"
      spDc: "${SPOTIFY_SP_DC:-}"
      countryCode: "${SPOTIFY_COUNTRY_CODE:-US}"
    applemusic:
      countryCode: "${APPLE_MUSIC_COUNTRY_CODE:-US}"
      mediaAPIToken: "${APPLE_MUSIC_MEDIA_API_TOKEN:-}"
