server:
  port: 2333
  address: 0.0.0.0
  password: ${LAVALINK_SERVER_PASSWORD:-youshallnotpass}
  sources:
    youtube: true
    bandcamp: true
    soundcloud: true
    twitch: true
    vimeo: true
    http: true
    local: false
  filters:
    volume: true

lavalink:
  server:
    password: ${LAVALINK_SERVER_PASSWORD:-youshallnotpass}
    player-update-interval: 5
    soundcloud:
      client-id: ''
  plugins: []
