server:
  http_listen_port: 3200
  log_level: info

distributor:
  receivers:
    otlp:
      protocols:
        http:
        grpc:

ingester:
  max_block_bytes: 1048576
  max_block_duration: 5m
  trace_idle_period: 10s

compactor:
  compaction:
    block_retention: 24h

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
    wal:
      path: /var/tempo/wal

querier:
  max_concurrent_queries: 16

query_frontend:
  search:
    max_duration: 0s
